CREATE TABLE EMPLOYEES (
    EMP_ID SERIAL PRIMARY KEY,
    EMP_NAME TEXT,
    GENDER TEXT
);

INSERT INTO EMPLOYEES (EMP_NAME, GENDER) VALUES
('RAHUL', 'MALE'),
('PRIYA', 'FEMALE'),
('AMIT', 'MALE'),
('NEHA', 'FEMALE'),
('ARJUN', 'MALE'),
('SNEHA', 'FEMALE');

CREATE OR REPLACE PROCEDURE GET_EMPLOYEE_COUNT_BY_GENDER(
    IN IN_GENDER TEXT,
    OUT OUT_COUNT INT
)
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT COUNT(*)
    INTO OUT_COUNT
    FROM EMPLOYEES
    WHERE GENDER = IN_GENDER;

    RAISE NOTICE 'TOTAL EMPLOYEES WITH GENDER % = %', IN_GENDER, OUT_COUNT;
END;
$$;

CALL GET_EMPLOYEE_COUNT_BY_GENDER('FEMALE', NULL);
CALL GET_EMPLOYEE_COUNT_BY_GENDER('MALE', NULL);
